// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXNgU3XA9ewOcQ6Fognl-jM_3yk7dLfeI',
    appId: '1:490603851284:android:4d920c8eeea4ad4fa0c101',
    messagingSenderId: '490603851284',
    projectId: 'flutter-chat-app-e4227',
    databaseURL: 'https://flutter-chat-app-e4227-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chat-app-e4227.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMUQfIuo1m6iV-WHr87sv54fNMtxBesK8',
    appId: '1:490603851284:ios:881e7cc5acc66889a0c101',
    messagingSenderId: '490603851284',
    projectId: 'flutter-chat-app-e4227',
    databaseURL: 'https://flutter-chat-app-e4227-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chat-app-e4227.appspot.com',
    iosClientId: '490603851284-rbaq7p1vq0p2a17bcfien3ro7gvafvff.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
